### ISSUE TITLE
Using one CLI command to finish submit jcl and get it's return code

### ISSUE THREAD

**Issue by tiantn** [zowe/zowe-cli-ftp-plugin#46]
It is reasonable sending one submit request and get response from system. Now to get job return code need to send another request to system. So maybe comnine this two requests to one is more convenient for user.

**Comment by std4lqi** [comment]
We may allow user to specify the interval of job status query, like 5 seconds, or 10 seconds. And how many queries or how long before giving up.

**Comment by zFernand0** [comment]
Is there a possibility to "register" a listener (e.g. POST to URL) so that z/OS tells us when the job is complete? 
I'm thinking something similar to `X-IBM-Notification-URL` in [z/OS MF - Jobs APIs](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_PutSubmitJob.htm)

**Comment by std4lqi** [comment]
The scenario in my mind is that user puts multiple job submits in one shell script, executing one after another. The subsequent job may or may not depend on the early jobs' result. For now, users need write their own sleep/query/exit.

The callback URL might be good for Rest API, but not easy to use for command line tool. The users of zftp are more likely comfortable with the synchronized way than callback.
