### ISSUE TITLE
NPM v7 compatibility issues

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli-ftp-plugin#72]
Seems like `npm run installPlugin` fails of npm versions 7.6.3 and above.

While we look into it, maybe we should add a note in the README with a recommendation to use version 7.5.1 and below.

**Comment by tiantn** [comment]
Hi @zFernand0, I have a try with node v15.14.0 and npm v7.7.6. `npm install` is ok, `npm run build` and `npm run installPlugin` are ok but with warning. The warning message is `npm WARN npm npm does not support Node.js v15.14.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12, 13.
npm WARN npm You can find the latest version at https://nodejs.org/`

**Comment by t1m0thyj** [comment]
@zFernand0 Could you try deleting your local "node_modules" folder and rerunning `npm run installPlugin`? 😋 

I was able to reproduce an error at first:
```
Command Error:
Install Failed
Error Details:
Cannot read property '1' of null
```

but it was because I still had an old version of Imperative installed that's not compatible with npm@7. After deleting my local "node_modules" folder, the command worked.

**Comment by zFernand0** [comment]
After clearing node_modules, I tried with node 15 and node 16 (with npm versions 7.6.3 and 7.10.0) and they both worked.
Thanks @tiantn and @t1m0thyj 😋 
Closing
